### ISSUE TITLE
Clean Videos list

### ISSUE THREAD

**Issue by g6807952** [XrXr/YoutubeSubscriptionChecker#15]
Number is reaching 1000 and to clean a list, remove individual videos from the list would be terrific.

**Comment by XrXr** [comment]
With the latest version, you can hold `ctrl` (`command` if you are on a Mac) and then click on a video to skip it without opening it.

The latest version can be downloaded [here](https://addons.mozilla.org/en-US/firefox/addon/youtube-subscription-checker/versions/)
