### ISSUE TITLE
Use SDK for button badging

### ISSUE THREAD

**Issue by Sek0n** [XrXr/YoutubeSubscriptionChecker#17]
![Badge](http://i.imgur.com/AuLfs5R.jpg)

Is this normal? I installed the addon on my PC and laptop, and both do this. Tried it without my theme/styles as well, but still it shows like this.

If this is normal, any chance of adding a badge background to it similar to the others?

Thanks

**Comment by XrXr** [comment]
Yes, that is the normal behaviour as of now.

When I wrote the part of code which did the icon badging, there wasn't a standardized API for it, so I rolled my own.

I will update it to use the standard lib. Thanks for noticing, thanks for being picky about it, I would have never notice that the added an API for it!

**Comment by Sek0n** [comment]
Cool, and No problem. 

Thanks for the great extension. :)
