### ISSUE TITLE
Subscription list is repeatedly erased

### ISSUE THREAD

**Issue by FredThompsonII** [XrXr/YoutubeSubscriptionChecker#20]
For some reason, the jetpack for this subscription list is being erased. I'm not sure why.
[YouTube Subscription Checker 2016-03-11.txt](https://github.com/XrXr/YoutubeSubscriptionChecker/files/288085/YouTube.Subscription.Checker.2016-03-11.txt)

**Comment by XrXr** [comment]
It's a known issue, the storage api we are using currently is extremely bad with  data corruption.
I am working on an update which should address the issue. A beta version will be released by the end of next week. see #19

**Comment by XrXr** [comment]
To anyone reading, [version 2.3.0](https://github.com/XrXr/YoutubeSubscriptionChecker/releases/tag/v2.3.0) is released. It should fix this issue, please help me verify by updating to it.

I will be using it for at least a few weeks before it is released on addons.mozilla.org

**Comment by FredThompsonII** [comment]
Great, thanks. I'm updating and running v 2.3.0 now.

On 5/31/2016 11:16 PM, Alan Wu wrote:
>
> To anyone reading, version 2.3.0 
> <https://github.com/XrXr/YoutubeSubscriptionChecker/releases/tag/v2.3.0> 
> is released. It should fix this issue, please help me verify by 
> updating to it.
>
> I will be using it for at least a few weeks before it is released on 
> addons.mozilla.org
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/XrXr/YoutubeSubscriptionChecker/issues/20#issuecomment-222882021>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/APt-p7AdaljIox751R0lKZ48LHj3XvGnks5qHPl-gaJpZM4IpMI4>.
>


-- 
   -=*=-

   Fred Thompson

   utils@mindspring.com

**Comment by XrXr** [comment]
[v2.3.1-beta.1](https://github.com/XrXr/YoutubeSubscriptionChecker/releases/tag/v2.3.1-beta.1) is released. It fixes some major issues in 2.3.0, including video wipe when removing channel.

**Comment by XrXr** [comment]
[v2.3.1](https://github.com/XrXr/YoutubeSubscriptionChecker/releases/tag/v2.3.1) was sent to AMO for review.

Thank you to anyone who tested beta versions, and make sure to follow the steps for updating :)
