### ISSUE TITLE
Port to WebExtension

### ISSUE THREAD

**Issue by ImAnnoying** [XrXr/YoutubeSubscriptionChecker#22]
With the release of Firefox 57 in November, all addons that are not WebExtensions will no longer run: https://blog.mozilla.org/addons/2017/02/16/the-road-to-firefox-57-compatibility-milestones/

**Comment by ImAnnoying** [comment]
Also this: https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing

**Comment by XrXr** [comment]
Porting effort is ongoing on the [web-extensions branch](/XrXr/YoutubeSubscriptionChecker/tree/web-extensions) branch :)

**Comment by ImAnnoying** [comment]
Thank goodness. I can't imagine my life without this addon 😁
