### ISSUE TITLE
Incompatible with 57 nightly builds

### ISSUE THREAD

**Issue by diizzyy** [XrXr/YoutubeSubscriptionChecker#26]
Hi,

Many thanks for this addon! Is there a possibility that you can have a look at why it isn't compatible with nightly builds?

Best regards
Daniel

**Comment by XrXr** [comment]
Sorry about the delay, I will make a build for 57 tomorrow.
Personally, I've been using release for the last little bit because I'm not sure I'm ready to give up on a few add-ons I like a lot.

**Comment by XrXr** [comment]
New version is out! https://addons.mozilla.org/en-US/firefox/addon/youtube-subscription-checker/versions/?page=1#version-2.4.1

**Comment by diizzyy** [comment]
Awesome, thanks!
Seems to work just fine! :-)
