### ISSUE TITLE
release for icecat

### ISSUE THREAD

**Issue by Joseph65** [XrXr/YoutubeSubscriptionChecker#27]
are you going to release the addon for browsers like icecat that are older versions of firefox
i think the latest icecat is based on 52 version

**Comment by XrXr** [comment]
I just tried running the latest version on IceCat by installing from AMO and it seems to work fine, so I think there is no special work needed on my part to support IceCat. I will wait for a video or two to come in but I don't think anything can go wrong.
The only other Firefox fork I know is PaleMoon. Supporting PaleMoon will take a lot of work as it doesn't support the addon sdk nor WebExtension. I don't think I will be supporting Palemoon.
