### ISSUE TITLE
not able to add a playlist

### ISSUE THREAD

**Issue by life22v** [XrXr/YoutubeSubscriptionChecker#28]
Hi, 

Excellent Tool. Thanks for developing this

Suggestion1: Scenario- 3 New videos has arrived. It show notification no '3'. Then i clicked on the icon, which takes me to the page, where i can see 3 new videos. Then i click on video 1,  and watch it, then the notification no changes to 2. Now i dont want to watch the 2nd video as i didnt find the content appealing. and i want to watch the 3rd content later. here is the issue. you may consider adding a option button or  i could 'Right click' on the video 2 and mark it as 'remove'. And right click on the 3rd video and  'watch later', and it should also bring the notification no to 'zero'. 

Suggestion2: I am able to add channels which only has one playlist. But, There is no option to add a specific Playlist if the youtube channel has multiple playlist. For e.g. many news channels. 

For e.g. this channel has many playlists
https://www.youtube.com/channel/UCYPvAwZP8pZhSMW8qs7cVCw/playlists

But, I only like to add a Specific playlist, lets say, ‘to the point’
https://www.youtube.com/watch?v=6qALm_jSKrI&list=PLPPKwCCueQ_DEyfmBZSV_nY2CdqB7oQy1

Same issue persists when i try to any sites which has many playlists. 

I used to use a similar tool on google chrome (YouTube Notifications by Wassup789). In the google chrome tool, I could just paste this specific playlist, then it will add this playlist, see attached image for ref. you may try to incorporate such a feature in this tool as well. 

Suggestion3:  My dream option would be to download all the videos automatically so i can watch them offline while i travel. If its hard, try if its possible to integrate this tool with IDM (Internet DOnwload Manger) to download videos automatically 

Appreciate if u could fix this. Thanks. Keep up the good work

**Comment by XrXr** [comment]
For suggestion 1, if you click on a video while holding down control, it dismisses it. I don't think I want to add a watch later queue to the addon though -- just leave the video in there.

For checking for playlists, I looked into this a bit, and it's not quite feasible to do well with the current Youtube API. I looked at how the Chrome extension you mentioned does it and tried that for a bit. Unfortunately I found that sometimes it misses new videos. Basically to do it well I would have to get all items in the playlist every time I check. Fetching that much stuff will make the addon stop working for everyone as there is a quota.

I would suggest trying out the filtering function that's already here.

For the downloading thing, it's way outside the scope of this addon, sorry.
