### ISSUE TITLE
"clear my data" not working and can't ffind website to delete manually.

### ISSUE THREAD

**Issue by fabionar** [XrXr/YoutubeSubscriptionChecker#29]
Failed to open internal database

I was not able to access the internal database which stores all your data. This is likely due to file corruption or some other catasrophic event.

You can try running file system repair tools on your system which might fix the issue. If all else fail, you can delete the corrupted database by typing clear my data in the input below

"Failed to delete the database. You may need to manually delete the database.
Instructions can be found on the add-on's website"

**Comment by XrXr** [comment]
If you downgrade Firefox from 57 to any version below that it will do this. Only 57 and up can read the data once you upgrade. Mozilla just decided to do this; it's beyond my control. If you do want to downgrade, you can upgrade to 57, use the export feature in the addon, then import the data into an older Firefox

If all else fails: **execute at your own risk**
- Go to about:profiles, click "open directory" for the root directory of the the default profile
- Make a backup of this folder, just in case you misfire when deleting
- Shutdown Firefox completely. I recommend going through the menus.
- Delete `storage.sqlite` and `storage/default/moz-extension+++5e6a782a-e7d5-438f-a45d-a9387d302362`
- Open Firefox again. It will take a moment before the addon becomes responsive, Firefox is not used to this kind situation.

**Comment by fabionar** [comment]
Thanks.
