### ISSUE TITLE
TwitterSubscriptionChecker

### ISSUE THREAD

**Issue by fabionar** [XrXr/YoutubeSubscriptionChecker#31]
Please, make one. The idea is fantastic.

**Comment by XrXr** [comment]
https://twitter.com/settings/web_notifications I think tweeter has this built in. I'm not the right person to ask for this though -- I don't really use Tweeter much :)

**Comment by fabionar** [comment]
Twitter has a policy to block accounts based on weird criteria.
I always end up losing my subscriptions.
