### ISSUE TITLE
req: display of direct URLs

### ISSUE THREAD

**Issue by FredThompsonII** [XrXr/YoutubeSubscriptionChecker#34]
Please add a way to see the direct URLs for the displayed thumbnails. This could be a button which copies a list to the clipboard or a text display of some sort.

I ask because the various FF addons for copying link don't work on local pages, even if those addons have tab permissions.

**Comment by XrXr** [comment]
Hi Fred, first of all, thank you for using my extension. I remember that you requested this feature in #33 and I rejected it back then. My judgement on this hasn't changed, but I have something for you.

You can go to https://jqplay.org/s/phmy8taWCu, and paste in an export of your data in the extension's setting, you should get a list of links. I hope this solves your problem. Use at your own risk :)
