### ISSUE TITLE
Doesn't work in FF 68.0.2 on Linux Mint

### ISSUE THREAD

**Issue by terr72** [XrXr/YoutubeSubscriptionChecker#35]
I can add and remove channels but it doesn't show any videos at all, no matter if I click on individual channels or 'all channels'. Notifications also don't work.

**Comment by terr72** [comment]
I just tried in two Windows environments with FF 68.0.2 with the same results.
It seems like Youtube Checker doesn't work at all with the current version of Firefox

**Comment by XrXr** [comment]
What channels do you add? Sometimes the API the extension uses lags behind the youtube.com for a bit. I've been using the extension on Arch Linux on 68.0.2 and it works fine for the channels I watch.

**Comment by terr72** [comment]
The channels I'm subscribed to in the extension are:
AvE
my mechanics
TysyTube Restoration
goonzquad
Restore It
Rescue & Restore

goonzquad published a new video after I installed Youtube Checker and no notification came up.

**Comment by terr72** [comment]
As a sidenote: I'm also using uBlock Origin, I hope that doesn't interfere with the API(?).

**Comment by terr72** [comment]
I just disabled uBlock Origin, makes no difference.
Attached you can find a screenshot of what it looks like.
![ytc](https://user-images.githubusercontent.com/23163919/63572662-a750f880-c583-11e9-9e7a-31f8f5814a91.png)

**Comment by terr72** [comment]
I just got my first successful notification!
Sorry, seems like there was a lag yesterday and it is solved now, you can close this case.
